[package]
name = "banyan_bao_proof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
time = "0.1.12"
bao = "0.12.0"
blake3 = "1.3.1"
rand = "0.8.5"
